bd656:
  outputs:
    dev:
      dataset: reddit
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../service-account-keys/envilink-7f4fac3111ec.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: envilink
      threads: 1
      type: bigquery
  target: dev
